version: "3.7"
services:
  projectforge-app:
    image: kreinhard/projectforge
    container_name: projectforge-app
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ${HOME}/ProjectForge:/ProjectForge
    entrypoint: ["java", "-Xms1g", "-Xmx1g", "-cp", "app:app/lib/*:/ProjectForge/plugins/*", "-Dprojectforge.setup=postgres", "-Dprojectforge.plugins.dir=/ProjectForge/plugins", "org.projectforge.start.ProjectForgeApplication"]
  depends_on:
      - projectforge-db
  projectforge-db:
    image: postgres:12.6
    container_name: projectforge-db
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${HOME}/ProjectForgeDB:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=***password***
      - POSTGRES_USER=projectforge
      - PGDATA=/var/lib/postgresql/data/pgdata
